name: nightly

on:
  # Run once daily at 4:45 AM UTC.
  schedule:
    - cron: "45 04 * * */1"

  # Allow manually-triggered runs.
  workflow_dispatch:

jobs:
  build:
    matrix:
      llvm-ref: [ main, llvmorg-20.1.0-rc1 ]
      android-platform: [ android-28 ]

    uses: ./.github/workflows/test-lldb.yml
    with:
      llvm-ref: ${{ matrix.llvm-ref }}
      android-platform: ${{ matrix.android-platform }}
