name: nightly

on:
  # Run once daily at 4:45 AM UTC.
  schedule:
    - cron: "45 04 * * */1"

  # Allow manually-triggered runs.
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/test-lldb.yml
